version: "3.9"

services:
  nginx:
    image: nginx:alpine
    container_name: udpstuff-nginx
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./hls:/usr/share/nginx/hls:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
